project_name: qubesome
builds:
  - id: qubesome
    binary: qubesome
    main: main.go
    flags:
    - -trimpath
    ldflags:
      - -s -w
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - riscv64
    env:
      - CGO_ENABLED=0

archives:
  - id: default
    format: binary

signs:
  - cmd: cosign
    certificate: '${artifact}.pem'
    args:
      - sign-blob
      - '--yes'
      - '--output-signature=${signature}'
      - '--output-certificate=${certificate}'
      - '--bundle=${artifact}.bundle'
      - '${artifact}'
    artifacts: checksum
    output: true

source:
  enabled: true
  name_template: '{{ .ProjectName }}_{{ .Version }}_source'

sboms:
  - id: source
    artifacts: source
    documents:
      - '{{ .ProjectName }}_{{ .Version }}_sbom.spdx.json'

release:
  extra_files:
    - glob: ./**/*.bundle
