version: 2
project_name: qubesome
builds:
  - id: qubesome
    binary: qubesome
    main: cmd/qubesome/main.go
    flags:
    - -trimpath
    ldflags:
      - -s -w
      - -X github.com/qubesome/cli/cmd/cli.version={{.Version}}
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - riscv64
    env:
      - CGO_ENABLED=0

archives:
  - formats: [ 'binary' ]

signs:
  - cmd: cosign
    signature: "${artifact}.sigstore.json"
    args:
      - sign-blob
      - '--yes'
      - '--new-bundle-format=true'
      - '--bundle=${signature}'
      - '${artifact}'
    artifacts: checksum
    output: true

source:
  enabled: true
  name_template: '{{ .ProjectName }}_{{ .Version }}_source'

sboms:
  - id: source
    artifacts: source
    documents:
      - '{{ .ProjectName }}_{{ .Version }}_sbom.spdx.json'
