// Command syscallgen writes a syscall name to number table for each
// supported architecture.
//
// There is no such table in the standard library. The numbers are taken
// from golang.org/x/sys/unix, whose zsysnum files are generated from the
// kernel headers, so qubesome does not maintain a copy of the numbering.
package main

import (
	"bufio"
	"context"
	"fmt"
	"go/format"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"runtime"
	"sort"
	"strconv"
	"strings"
)

var arches = []string{"amd64", "arm64"}

// auditArch holds the AUDIT_ARCH_* value the kernel reports in
// seccomp_data.arch for each architecture.
var auditArch = map[string]uint32{
	"amd64": 0xc000003e, // AUDIT_ARCH_X86_64
	"arm64": 0xc00000b7, // AUDIT_ARCH_AARCH64
}

var sysRe = regexp.MustCompile(`^\s*SYS_([A-Z0-9_]+)\s+=\s+(\d+)$`)

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "syscallgen:", err)
		os.Exit(1)
	}
}

func run() error {
	sysUnixDir, err := sysUnixDir()
	if err != nil {
		return err
	}

	outDir, err := seccompDir()
	if err != nil {
		return err
	}

	for _, arch := range arches {
		nums, err := parse(filepath.Join(sysUnixDir, "zsysnum_linux_"+arch+".go"))
		if err != nil {
			return err
		}
		if err := write(outDir, arch, nums); err != nil {
			return err
		}
		fmt.Printf("syscallgen: %s: %d syscalls\n", arch, len(nums))
	}

	return nil
}

// sysUnixDir locates the unix package of the golang.org/x/sys version this
// module already depends on, so the table cannot drift from the module the
// rest of the code links against.
func sysUnixDir() (string, error) {
	out, err := exec.CommandContext(context.Background(), "go", "list", "-m", "-f", "{{.Dir}}", "golang.org/x/sys").Output()
	if err != nil {
		return "", fmt.Errorf("failed to locate golang.org/x/sys: %w", err)
	}
	return filepath.Join(strings.TrimSpace(string(out)), "unix"), nil
}

// seccompDir returns the internal/seccomp package directory, resolved from
// this generator's own source location rather than the process's current
// working directory. go generate runs generators with the working
// directory of the file carrying the //go:generate directive, but the
// generator may also be invoked directly (for example from the repo
// root), so anchoring to its own source path keeps the output landing in
// the same place either way.
func seccompDir() (string, error) {
	_, thisFile, _, ok := runtime.Caller(0)
	if !ok {
		return "", fmt.Errorf("failed to determine generator source location")
	}
	// this file lives at <repo>/hack/syscallgen/main.go
	dir := filepath.Join(filepath.Dir(thisFile), "..", "..", "internal", "seccomp")
	return filepath.Clean(dir), nil
}

func parse(path string) (map[string]uint32, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, fmt.Errorf("failed to open %q: %w", path, err)
	}
	defer f.Close()

	nums := map[string]uint32{}
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		m := sysRe.FindStringSubmatch(scanner.Text())
		if m == nil {
			continue
		}
		n, err := strconv.ParseUint(m[2], 10, 32)
		if err != nil {
			return nil, fmt.Errorf("failed to parse %q in %q: %w", m[2], path, err)
		}
		nums[strings.ToLower(m[1])] = uint32(n)
	}
	if err := scanner.Err(); err != nil {
		return nil, fmt.Errorf("failed to read %q: %w", path, err)
	}
	if len(nums) == 0 {
		return nil, fmt.Errorf("no syscalls found in %q", path)
	}

	return nums, nil
}

func write(outDir, arch string, nums map[string]uint32) error {
	names := make([]string, 0, len(nums))
	for name := range nums {
		names = append(names, name)
	}
	sort.Strings(names)

	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by hack/syscallgen. DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "//go:build linux && %s\n\n", arch)
	fmt.Fprintf(&b, "package seccomp\n\n")
	fmt.Fprintf(&b, "const auditArch = %#x\n\n", auditArch[arch])
	fmt.Fprintf(&b, "var syscallNumbers = map[string]uint32{\n")
	for _, name := range names {
		fmt.Fprintf(&b, "\t%q: %d,\n", name, nums[name])
	}
	fmt.Fprintf(&b, "}\n")

	src, err := format.Source([]byte(b.String()))
	if err != nil {
		return fmt.Errorf("failed to gofmt generated source for %s: %w", arch, err)
	}

	path := filepath.Join(outDir, "zsyscalls_linux_"+arch+".go")
	return os.WriteFile(path, src, 0o600)
}
