// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: pkg/inception/proto/host.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type XdgOpenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *XdgOpenRequest) Reset() {
	*x = XdgOpenRequest{}
	mi := &file_pkg_inception_proto_host_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XdgOpenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XdgOpenRequest) ProtoMessage() {}

func (x *XdgOpenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_inception_proto_host_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XdgOpenRequest.ProtoReflect.Descriptor instead.
func (*XdgOpenRequest) Descriptor() ([]byte, []int) {
	return file_pkg_inception_proto_host_proto_rawDescGZIP(), []int{0}
}

func (x *XdgOpenRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type XdgOpenReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *XdgOpenReply) Reset() {
	*x = XdgOpenReply{}
	mi := &file_pkg_inception_proto_host_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XdgOpenReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XdgOpenReply) ProtoMessage() {}

func (x *XdgOpenReply) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_inception_proto_host_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XdgOpenReply.ProtoReflect.Descriptor instead.
func (*XdgOpenReply) Descriptor() ([]byte, []int) {
	return file_pkg_inception_proto_host_proto_rawDescGZIP(), []int{1}
}

type RunWorkloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workload      string                 `protobuf:"bytes,1,opt,name=workload,proto3" json:"workload,omitempty"`
	Args          string                 `protobuf:"bytes,2,opt,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunWorkloadRequest) Reset() {
	*x = RunWorkloadRequest{}
	mi := &file_pkg_inception_proto_host_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunWorkloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunWorkloadRequest) ProtoMessage() {}

func (x *RunWorkloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_inception_proto_host_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunWorkloadRequest.ProtoReflect.Descriptor instead.
func (*RunWorkloadRequest) Descriptor() ([]byte, []int) {
	return file_pkg_inception_proto_host_proto_rawDescGZIP(), []int{2}
}

func (x *RunWorkloadRequest) GetWorkload() string {
	if x != nil {
		return x.Workload
	}
	return ""
}

func (x *RunWorkloadRequest) GetArgs() string {
	if x != nil {
		return x.Args
	}
	return ""
}

type RunWorkloadReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunWorkloadReply) Reset() {
	*x = RunWorkloadReply{}
	mi := &file_pkg_inception_proto_host_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunWorkloadReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunWorkloadReply) ProtoMessage() {}

func (x *RunWorkloadReply) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_inception_proto_host_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunWorkloadReply.ProtoReflect.Descriptor instead.
func (*RunWorkloadReply) Descriptor() ([]byte, []int) {
	return file_pkg_inception_proto_host_proto_rawDescGZIP(), []int{3}
}

type FlatpakRunWorkloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workload      string                 `protobuf:"bytes,1,opt,name=workload,proto3" json:"workload,omitempty"`
	Args          string                 `protobuf:"bytes,2,opt,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlatpakRunWorkloadRequest) Reset() {
	*x = FlatpakRunWorkloadRequest{}
	mi := &file_pkg_inception_proto_host_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlatpakRunWorkloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlatpakRunWorkloadRequest) ProtoMessage() {}

func (x *FlatpakRunWorkloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_inception_proto_host_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlatpakRunWorkloadRequest.ProtoReflect.Descriptor instead.
func (*FlatpakRunWorkloadRequest) Descriptor() ([]byte, []int) {
	return file_pkg_inception_proto_host_proto_rawDescGZIP(), []int{4}
}

func (x *FlatpakRunWorkloadRequest) GetWorkload() string {
	if x != nil {
		return x.Workload
	}
	return ""
}

func (x *FlatpakRunWorkloadRequest) GetArgs() string {
	if x != nil {
		return x.Args
	}
	return ""
}

type FlatpakRunWorkloadReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlatpakRunWorkloadReply) Reset() {
	*x = FlatpakRunWorkloadReply{}
	mi := &file_pkg_inception_proto_host_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlatpakRunWorkloadReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlatpakRunWorkloadReply) ProtoMessage() {}

func (x *FlatpakRunWorkloadReply) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_inception_proto_host_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlatpakRunWorkloadReply.ProtoReflect.Descriptor instead.
func (*FlatpakRunWorkloadReply) Descriptor() ([]byte, []int) {
	return file_pkg_inception_proto_host_proto_rawDescGZIP(), []int{5}
}

var File_pkg_inception_proto_host_proto protoreflect.FileDescriptor

const file_pkg_inception_proto_host_proto_rawDesc = "" +
	"\n" +
	"\x1epkg/inception/proto/host.proto\x12\bqubesome\"\"\n" +
	"\x0eXdgOpenRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\x0e\n" +
	"\fXdgOpenReply\"D\n" +
	"\x12RunWorkloadRequest\x12\x1a\n" +
	"\bworkload\x18\x01 \x01(\tR\bworkload\x12\x12\n" +
	"\x04args\x18\x02 \x01(\tR\x04args\"\x12\n" +
	"\x10RunWorkloadReply\"K\n" +
	"\x19FlatpakRunWorkloadRequest\x12\x1a\n" +
	"\bworkload\x18\x01 \x01(\tR\bworkload\x12\x12\n" +
	"\x04args\x18\x02 \x01(\tR\x04args\"\x19\n" +
	"\x17FlatpakRunWorkloadReply2\xf8\x01\n" +
	"\fQubesomeHost\x12=\n" +
	"\aXdgOpen\x12\x18.qubesome.XdgOpenRequest\x1a\x16.qubesome.XdgOpenReply\"\x00\x12I\n" +
	"\vRunWorkload\x12\x1c.qubesome.RunWorkloadRequest\x1a\x1a.qubesome.RunWorkloadReply\"\x00\x12^\n" +
	"\x12FlatpakRunWorkload\x12#.qubesome.FlatpakRunWorkloadRequest\x1a!.qubesome.FlatpakRunWorkloadReply\"\x00B-Z+github.com/qubesome/cli/pkg/inception/protob\x06proto3"

var (
	file_pkg_inception_proto_host_proto_rawDescOnce sync.Once
	file_pkg_inception_proto_host_proto_rawDescData []byte
)

func file_pkg_inception_proto_host_proto_rawDescGZIP() []byte {
	file_pkg_inception_proto_host_proto_rawDescOnce.Do(func() {
		file_pkg_inception_proto_host_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_inception_proto_host_proto_rawDesc), len(file_pkg_inception_proto_host_proto_rawDesc)))
	})
	return file_pkg_inception_proto_host_proto_rawDescData
}

var file_pkg_inception_proto_host_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pkg_inception_proto_host_proto_goTypes = []any{
	(*XdgOpenRequest)(nil),            // 0: qubesome.XdgOpenRequest
	(*XdgOpenReply)(nil),              // 1: qubesome.XdgOpenReply
	(*RunWorkloadRequest)(nil),        // 2: qubesome.RunWorkloadRequest
	(*RunWorkloadReply)(nil),          // 3: qubesome.RunWorkloadReply
	(*FlatpakRunWorkloadRequest)(nil), // 4: qubesome.FlatpakRunWorkloadRequest
	(*FlatpakRunWorkloadReply)(nil),   // 5: qubesome.FlatpakRunWorkloadReply
}
var file_pkg_inception_proto_host_proto_depIdxs = []int32{
	0, // 0: qubesome.QubesomeHost.XdgOpen:input_type -> qubesome.XdgOpenRequest
	2, // 1: qubesome.QubesomeHost.RunWorkload:input_type -> qubesome.RunWorkloadRequest
	4, // 2: qubesome.QubesomeHost.FlatpakRunWorkload:input_type -> qubesome.FlatpakRunWorkloadRequest
	1, // 3: qubesome.QubesomeHost.XdgOpen:output_type -> qubesome.XdgOpenReply
	3, // 4: qubesome.QubesomeHost.RunWorkload:output_type -> qubesome.RunWorkloadReply
	5, // 5: qubesome.QubesomeHost.FlatpakRunWorkload:output_type -> qubesome.FlatpakRunWorkloadReply
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_inception_proto_host_proto_init() }
func file_pkg_inception_proto_host_proto_init() {
	if File_pkg_inception_proto_host_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_inception_proto_host_proto_rawDesc), len(file_pkg_inception_proto_host_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_inception_proto_host_proto_goTypes,
		DependencyIndexes: file_pkg_inception_proto_host_proto_depIdxs,
		MessageInfos:      file_pkg_inception_proto_host_proto_msgTypes,
	}.Build()
	File_pkg_inception_proto_host_proto = out.File
	file_pkg_inception_proto_host_proto_goTypes = nil
	file_pkg_inception_proto_host_proto_depIdxs = nil
}
