settings:
  defaultProfile: "untrusted"
  homedir: "~/.qubesome"

  runners:
    docker:
      baseCmd: docker --rm -d

    podman:
      baseCmd: podman --rm -d

    microVM:
      baseCmd: echo abc --rm -d
