// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: pkg/control/proto/control.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// name is the policy key, which is the single string the gateway's workloads
// map is keyed by. Profile and workload are not sent separately, otherwise
// two repositories would have to agree on how they are joined.
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_pkg_control_proto_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_control_proto_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_pkg_control_proto_control_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type RegisterReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReply) Reset() {
	*x = RegisterReply{}
	mi := &file_pkg_control_proto_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReply) ProtoMessage() {}

func (x *RegisterReply) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_control_proto_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReply.ProtoReflect.Descriptor instead.
func (*RegisterReply) Descriptor() ([]byte, []int) {
	return file_pkg_control_proto_control_proto_rawDescGZIP(), []int{1}
}

type UnregisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterRequest) Reset() {
	*x = UnregisterRequest{}
	mi := &file_pkg_control_proto_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterRequest) ProtoMessage() {}

func (x *UnregisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_control_proto_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterRequest.ProtoReflect.Descriptor instead.
func (*UnregisterRequest) Descriptor() ([]byte, []int) {
	return file_pkg_control_proto_control_proto_rawDescGZIP(), []int{2}
}

func (x *UnregisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UnregisterReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterReply) Reset() {
	*x = UnregisterReply{}
	mi := &file_pkg_control_proto_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterReply) ProtoMessage() {}

func (x *UnregisterReply) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_control_proto_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterReply.ProtoReflect.Descriptor instead.
func (*UnregisterReply) Descriptor() ([]byte, []int) {
	return file_pkg_control_proto_control_proto_rawDescGZIP(), []int{3}
}

type ReadyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadyRequest) Reset() {
	*x = ReadyRequest{}
	mi := &file_pkg_control_proto_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyRequest) ProtoMessage() {}

func (x *ReadyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_control_proto_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyRequest.ProtoReflect.Descriptor instead.
func (*ReadyRequest) Descriptor() ([]byte, []int) {
	return file_pkg_control_proto_control_proto_rawDescGZIP(), []int{4}
}

type ReadyReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadyReply) Reset() {
	*x = ReadyReply{}
	mi := &file_pkg_control_proto_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyReply) ProtoMessage() {}

func (x *ReadyReply) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_control_proto_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyReply.ProtoReflect.Descriptor instead.
func (*ReadyReply) Descriptor() ([]byte, []int) {
	return file_pkg_control_proto_control_proto_rawDescGZIP(), []int{5}
}

// Reload asks the gateway to re-read the policy file it was started with.
// The path is not carried: the gateway is handed its policy at start and is
// the only side that knows where the file landed inside its sandbox.
//
// The workload map is not part of the file and survives a reload. qubesome
// is the source of truth for it, and a reload that dropped it would leave
// running workloads unclassified.
type ReloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadRequest) Reset() {
	*x = ReloadRequest{}
	mi := &file_pkg_control_proto_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadRequest) ProtoMessage() {}

func (x *ReloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_control_proto_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadRequest.ProtoReflect.Descriptor instead.
func (*ReloadRequest) Descriptor() ([]byte, []int) {
	return file_pkg_control_proto_control_proto_rawDescGZIP(), []int{6}
}

type ReloadReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadReply) Reset() {
	*x = ReloadReply{}
	mi := &file_pkg_control_proto_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadReply) ProtoMessage() {}

func (x *ReloadReply) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_control_proto_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadReply.ProtoReflect.Descriptor instead.
func (*ReloadReply) Descriptor() ([]byte, []int) {
	return file_pkg_control_proto_control_proto_rawDescGZIP(), []int{7}
}

var File_pkg_control_proto_control_proto protoreflect.FileDescriptor

const file_pkg_control_proto_control_proto_rawDesc = "" +
	"\n" +
	"\x1fpkg/control/proto/control.proto\x12\acontrol\"?\n" +
	"\x0fRegisterRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"\x0f\n" +
	"\rRegisterReply\"'\n" +
	"\x11UnregisterRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x11\n" +
	"\x0fUnregisterReply\"\x0e\n" +
	"\fReadyRequest\"\f\n" +
	"\n" +
	"ReadyReply\"\x0f\n" +
	"\rReloadRequest\"\r\n" +
	"\vReloadReply2\x87\x02\n" +
	"\x0eGatewayControl\x12>\n" +
	"\bRegister\x12\x18.control.RegisterRequest\x1a\x16.control.RegisterReply\"\x00\x12D\n" +
	"\n" +
	"Unregister\x12\x1a.control.UnregisterRequest\x1a\x18.control.UnregisterReply\"\x00\x125\n" +
	"\x05Ready\x12\x15.control.ReadyRequest\x1a\x13.control.ReadyReply\"\x00\x128\n" +
	"\x06Reload\x12\x16.control.ReloadRequest\x1a\x14.control.ReloadReply\"\x00B+Z)github.com/qubesome/cli/pkg/control/protob\x06proto3"

var (
	file_pkg_control_proto_control_proto_rawDescOnce sync.Once
	file_pkg_control_proto_control_proto_rawDescData []byte
)

func file_pkg_control_proto_control_proto_rawDescGZIP() []byte {
	file_pkg_control_proto_control_proto_rawDescOnce.Do(func() {
		file_pkg_control_proto_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_control_proto_control_proto_rawDesc), len(file_pkg_control_proto_control_proto_rawDesc)))
	})
	return file_pkg_control_proto_control_proto_rawDescData
}

var file_pkg_control_proto_control_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pkg_control_proto_control_proto_goTypes = []any{
	(*RegisterRequest)(nil),   // 0: control.RegisterRequest
	(*RegisterReply)(nil),     // 1: control.RegisterReply
	(*UnregisterRequest)(nil), // 2: control.UnregisterRequest
	(*UnregisterReply)(nil),   // 3: control.UnregisterReply
	(*ReadyRequest)(nil),      // 4: control.ReadyRequest
	(*ReadyReply)(nil),        // 5: control.ReadyReply
	(*ReloadRequest)(nil),     // 6: control.ReloadRequest
	(*ReloadReply)(nil),       // 7: control.ReloadReply
}
var file_pkg_control_proto_control_proto_depIdxs = []int32{
	0, // 0: control.GatewayControl.Register:input_type -> control.RegisterRequest
	2, // 1: control.GatewayControl.Unregister:input_type -> control.UnregisterRequest
	4, // 2: control.GatewayControl.Ready:input_type -> control.ReadyRequest
	6, // 3: control.GatewayControl.Reload:input_type -> control.ReloadRequest
	1, // 4: control.GatewayControl.Register:output_type -> control.RegisterReply
	3, // 5: control.GatewayControl.Unregister:output_type -> control.UnregisterReply
	5, // 6: control.GatewayControl.Ready:output_type -> control.ReadyReply
	7, // 7: control.GatewayControl.Reload:output_type -> control.ReloadReply
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_control_proto_control_proto_init() }
func file_pkg_control_proto_control_proto_init() {
	if File_pkg_control_proto_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_control_proto_control_proto_rawDesc), len(file_pkg_control_proto_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_control_proto_control_proto_goTypes,
		DependencyIndexes: file_pkg_control_proto_control_proto_depIdxs,
		MessageInfos:      file_pkg_control_proto_control_proto_msgTypes,
	}.Build()
	File_pkg_control_proto_control_proto = out.File
	file_pkg_control_proto_control_proto_goTypes = nil
	file_pkg_control_proto_control_proto_depIdxs = nil
}
