name: fuzz tests

on:
  push:
  workflow_dispatch:

  schedule:
    - cron: "0 7 * * 6"

permissions: {}

jobs:
  fuzz:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      actions: read # for cache access
    env:
      FUZZ_TIME: 10m

    steps:
      - name: Checkout
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2 # v4.2.2

      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: stable

      - name: Set environment variable based on trigger
        run: |
          if [[ "${{ github.event_name }}" != "push" ]]; then
            echo "FUZZ_TIME=30m" >> $GITHUB_ENV
          fi

      - name: Fuzzing
        uses: form3tech-oss/go-ci-fuzz/ci/github-actions/fuzz@4663eaaadb263d2621592c62681dac7f7002d582
        with:
          fuzz-time: ${{ env.FUZZ_TIME }}
          fail-fast: true
          version: 0.1.3
