name: release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write # create GH releases
  id-token: write # ephemeral keys (a.k.a. "keyless") signing

jobs:
  goreleaser:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - uses: anchore/sbom-action/download-syft@v0.15.0
      - uses: sigstore/cosign-installer@v3.4.0

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
